#!/bin/bash
set -x



OI=/var/lib/openinfoman
USERNAME=oi
BASEX=$OI/bin/basex


REPOS=("dxf2csd.xqm" "dxf_1_0.xqm")


for REPO in ${REPOS[@]}
do
   INST="REPO INSTALL ${OI}/repo-src/${REPO}"
   $BASEX -Vc "${INST}"
done

chown -R $USERNAME:$USERNAME $OI


